export const POST_TEMPLATES = {
  normal: [
    "Just finished work! Time to relax 🌙",
    "Coffee break ☕ anyone?",
    "Beautiful day outside! ☀️",
    "Movie night vibes 🎬",
    "Cooking something delicious tonight 🍳",
    "Weekend plans? Anyone want to hang out?",
    "Just got home, so tired 😴",
    "Morning workout done! 💪",
    "Reading a good book 📚",
    "New playlist who dis 🎵",
    "Can't believe it's already Friday!",
    "Trying a new recipe tonight 🍝",
    "Sunday funday! 🎉",
    "Netflix and chill mode: activated",
    "Who else loves rainy days? 🌧️",
    "Just adopted a plant! Meet Leaf 🌿",
    "Brainstorming dinner ideas...",
    "That feeling when you finally sit down after a long day",
    "Anyone else a night owl? 🦉",
    "Productive day! Checked everything off my list ✅",
    "Procrastination level: expert 🏆",
    "Just discovered a new favorite song!",
    "Cleaning motivation: where are you? 🧹",
    "Thinking about taking up a new hobby",
    "That post-coffee clarity though ✨",
    "Lazy Sunday energy 🛋️",
    "Can we just skip to the weekend already?",
    "Feeling grateful today 🙏",
    "Self-care Sunday in progress 🛁",
    "Who needs sleep when you have memes? 😂",
  ],
  bladderRelated: [
    "Okay my bladder is being SO dramatic right now 😩",
    "Why do I always need to go when I'm busy?? 🙄",
    "Holding it like it's an extreme sport 🏆",
    "Note to self: don't drink 3 coffees in a row ☕☕☕",
    "My bladder has its own agenda, I swear",
    "Currently doing the potty dance 💃",
    "Bladder: 1, Me: 0 😫",
    "Someone invent a teleportation bathroom PLEASE 🚽✨",
    "Crossing legs is my cardio today 🦵",
    "The urge is real right now...",
    "Why is every bathroom occupied when I need it most??",
    "Playing a dangerous game called 'maybe I don't need to go yet'",
    "My bladder and I are not on speaking terms",
    "That moment when you realize you drank too much water 💧",
    "Holding contest with myself: I'm losing",
    "Send prayers (or a portable toilet) 🙏",
    "Bladder update: still winning this battle... barely",
    "If I disappear, I found a bathroom",
    "The walk of shame to the bathroom again...",
    "Current status: doing the holding dance 💃",
    "My bladder has a vendetta against me",
    "Why did I think 'just one more cup' was a good idea?",
    "Bathroom break? More like bathroom SPRINT 🏃‍♀️",
    "Note to future self: empty bladder BEFORE leaving",
    "This is fine. Everything is fine. 🙃",
    "Bladder容量: over 9000!!! 📈",
    "Playing chicken with my bladder and losing",
    "When you're 5 minutes from home and the urge hits 💀",
    "Current mood: 🚽🚽🚽",
    "Holding it together... literally",
  ],
  fullBladderPreference: [
    "Okay I'm FULL but honestly? Kinda vibing with it 😌",
    "My bladder is at max capacity and I'm weirdly okay with it",
    "Full bladder energy is different, not gonna lie",
    "I should go but... I'm kinda enjoying the pressure? 🤔",
    "Living my best (full) life rn",
    "Full bladder = clear mind, apparently?",
    "Everyone's freaking out but I'm just here feeling great ✨",
    "The fuller I get, the more zen I become 🧘‍♀️",
    "People don't understand the comfort of a full bladder",
    "Currently at 90% and feeling absolutely fine",
    "My friends are worried, I'm thriving",
    "Full bladder supremacy 🏆",
    "They said 'go to the bathroom' I said 'nah I'm good'",
    "This feeling > everything else",
    "Peak performance achieved (bladder-wise)",
    "In my full bladder era 💅",
    "Who needs therapy when you have bladder pressure?",
    "Comfort level: maximum",
    "Full and focused, that's the motto",
    "The pressure is... pleasant? Is that weird?",
    "Living on the edge (of my bladder capacity)",
    "Full bladder club, where we at? 🙋‍♀️",
    "This is what peak performance looks like",
    "Stress? What stress? I'm perfectly full 🧘‍♀️",
    "My bladder is my therapist",
    "In my element (a full one)",
    "Full bladder, clear mind, good vibes",
    "They call it holding, I call it thriving",
    "Maximum capacity, maximum comfort",
    "The art of being comfortably full 🎨",
  ],
  emptyBladderAnxiety: [
    "Why do I feel so empty and anxious?? 😟",
    "My bladder feels weirdly empty and it's stressing me out",
    "Anyone else get anxious when they don't feel full down there?",
    "Need to drink something, feeling weird without that pressure",
    "Empty bladder = empty soul? Is that a thing? 😅",
    "Feeling naked without my usual fullness",
    "Why does empty feel so wrong??",
    "Something's missing and it's that familiar pressure",
    "Can someone pass the water? Feeling off without my full bladder",
    "Is it weird that I miss being full? 🤔",
    "Empty bladder anxiety is real, guys",
    "Need that comfortable full feeling back",
    "Drinking water like it's my job (because it kind of is)",
    "The emptiness is... unsettling",
    "Where did my comfortable pressure go? 😢",
    "Feeling incomplete without a full bladder",
    "This empty feeling is making me anxious",
    "Need to fill up, something's off",
    "Empty bladder = bad vibes only",
    "Chugging water to feel normal again",
    "Why does not being full feel so wrong?",
    "Seeking that familiar comfortable pressure",
    "Empty bladder gang, where you at? (sadly alone)",
    "Need to fix this empty feeling ASAP",
    "Something's missing and I know what it is 💧",
    "Back to empty again, ugh 😩",
    "The anxiety of not being full is real",
    "Need that comfortable pressure back",
    "Feeling off without my usual fullness",
    "Empty bladder problems nobody asked for",
  ],
};

export const COMMENT_TEMPLATES = {
  supportive: [
    "omg same! 😩",
    "how are you holding that??",
    "sending strength 💪",
    "you're a legend for this",
    "I feel this in my soul",
    "relatable content 10/10",
    "queen of holding 👑",
    "this is so me rn",
    "goals honestly",
    "living vicariously through you",
  ],
  funny: [
    "my bladder sends its regards 💀",
    "this is why I can't have nice things",
    "bladder problems unite! 🤝",
    "the struggle is so real",
    "I'm crying (and not just from the urge)",
    "why is this so accurate 😂",
    "my bladder heard you and is now protesting",
    "never has a post been more true",
    "I laughed then immediately needed to go",
    "the universe heard you and said 'hold this'",
  ],
  advice: [
    "try crossing your legs!",
    "distraction is key, trust me",
    "deep breaths help!",
    "have you tried sitting differently?",
    "maybe go now before it's too late?",
    "pro tip: don't think about bathrooms",
    "remember to stay hydrated though!",
    "maybe find a bathroom soon?",
    "the bathroom dance is real 💃",
    "you got this! (but maybe go soon)",
  ],
  impressed: [
    "that's insane capacity!",
    "how?? just how??",
    "you're built different",
    "this is next level",
    "actual goals right here",
    "teach me your ways 🙏",
    "legendary behavior",
    "the dedication is real",
    "I could never, mad respect",
    "this is peak performance",
  ],
};

export const FOLLOWER_SUGGESTION_TEMPLATES = [
  "Try holding for another hour!",
  "Drink a big glass of water right now 💧",
  "Go live when you hit 90%!",
  "Try the full bladder preference trait",
  "Cross your legs and pace around",
  "Lock your sphincter for 30 min",
  "Post about your current state!",
  "Try holding through a whole movie",
  "Drink 3 cups of coffee in a row ☕",
  "Go to work without going first",
  "Try sitting for 2 hours straight",
  "Attempt a 4-hour hold challenge",
  "Go live during a meeting!",
  "Try holding while gaming",
  "Drink only diuretics today",
  "Attempt to reach max capacity",
  "Go live when you're desperate",
  "Try holding through a car ride",
  "Post hourly updates!",
  "Challenge: no bathroom for 6 hours",
  "Try holding while exercising",
  "Go live during a meal",
  "Attempt to break your record",
  "Try the sphincter lock challenge",
  "Post your current volume!",
  "Try holding through the night",
  "Go live at maximum capacity",
  "Try holding while watching a movie",
  "Attempt a full day hold",
  "Post your training progress!",
];

export const DONATION_MESSAGES = [
  "Keep going! You're amazing! 💪",
  "This is the best stream ever!",
  "How are you still holding?? 😱",
  "You're an inspiration!",
  "Sending support! 🙏",
  "This is incredible content!",
  "You're a legend!",
  "Mad respect! 🏆",
  "Never stop streaming!",
  "You're the best! ❤️",
  "This is so relatable!",
  "Queen behavior 👑",
  "Goals! 🎯",
  "You got this!",
  "Incredible endurance!",
  "So proud of you!",
  "This is amazing!",
  "Keep it up! 💪",
  "You're crushing it!",
  "Best streamer ever!",
];

export const MEGA_INFLUENCER_NAMES = [
  "BladderKing",
  "HoldingMaster",
  "StreamQueen",
  "EnduranceGod",
  "CapacityLegend",
];
